// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoxPqYywFP5bIki03ED-ACYLy-OUvNDFo',
    appId: '1:111799079630:web:d07f90c8acc3a7de09369f',
    messagingSenderId: '111799079630',
    projectId: 'poker-chip-14428',
    authDomain: 'poker-chip-14428.firebaseapp.com',
    storageBucket: 'poker-chip-14428.appspot.com',
    measurementId: 'G-1B94DWWSZ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCe7QIikYa7QldE5e46lCCIr5RWsITwhx0',
    appId: '1:111799079630:android:2b85450861b55cac09369f',
    messagingSenderId: '111799079630',
    projectId: 'poker-chip-14428',
    storageBucket: 'poker-chip-14428.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjxx2LdSwNMfedziOZdPwCxMkb2tP2A18',
    appId: '1:111799079630:ios:e94da6160f509dc909369f',
    messagingSenderId: '111799079630',
    projectId: 'poker-chip-14428',
    storageBucket: 'poker-chip-14428.appspot.com',
    iosBundleId: 'com.poker.chip',
  );
}
